stages:
 - build
 - deploy

variables:
  KERNEL_RELEASE: "4.4.38-minit"
  DRIVER_VERSION: "0.1.0-1"
  UBUNTU_VERSION: "xenial"

compile:
  image: docker-registry.oxfordnanolabs.local:5000/kernel-dev-aarch64
  tags:
    - linux_aarch64
  stage: build
  script:
    - COMPILED_DRIVER_PACKAGE=1 KERNELRELEASE=${KERNEL_RELEASE} make dist-deb
  artifacts:
    paths:
    - ./ont-minion1c-driver-${KERNEL_RELEASE}_${DRIVER_VERSION}~${UBUNTU_VERSION}_arm64.deb
    - ./ont-minion1c-driver-dev_${DRIVER_VERSION}~${UBUNTU_VERSION}_all.deb
    - ./ont-minion1c-driver-utils_${DRIVER_VERSION}~${UBUNTU_VERSION}_arm64.deb
    - ./ont-minion1c-driver_${DRIVER_VERSION}~${UBUNTU_VERSION}.dsc
    - ./ont-minion1c-driver_${DRIVER_VERSION}~${UBUNTU_VERSION}.tar.gz

.publish: &publish
  image: docker-registry.oxfordnanolabs.local:5000/ont-base-ubuntu:16.04
  when: manual
  tags:
    - linux
  only:
    - master
    - tags
  script:
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$DEB_REPO_KEY")
   - scp -o StrictHostKeyChecking=no ont-minion1c-driver*.deb hudson@deb-repo.oxfordnanolabs.local:/var/www/apt/${UBUNTU_VERSION}-${CHANNEL}-minit

publish_unstable:
  <<: *publish
  stage: deploy
  variables:
    CHANNEL: unstable

publish_stable:
  <<: *publish
  stage: deploy
  variables:
    CHANNEL: stable
