stages:
 - build
 - deploy

variables:
  KERNEL_RELEASE: "4.4.38-minit"
  DRIVER_VERSION: "0.3.0-1"
  UBUNTU_VERSION: "xenial"

compile:
  image: docker-registry.oxfordnanolabs.local:5000/kernel-dev-aarch64
  tags:
    - linux_aarch64
  stage: build
  script:
    - COMPILED_DRIVER_PACKAGE=1 KERNELRELEASE=${KERNEL_RELEASE} make dist-deb
  artifacts:
    paths:
    - ./ont-minion1c-driver-${KERNEL_RELEASE}_${DRIVER_VERSION}~${UBUNTU_VERSION}_arm64.deb
    - ./ont-minion1c-driver-dev_${DRIVER_VERSION}~${UBUNTU_VERSION}_all.deb
    - ./ont-minion1c-driver-utils_${DRIVER_VERSION}~${UBUNTU_VERSION}_arm64.deb
    - ./ont-minion1c-driver_${DRIVER_VERSION}~${UBUNTU_VERSION}.dsc
    - ./ont-minion1c-driver_${DRIVER_VERSION}~${UBUNTU_VERSION}.tar.gz

.publish: &publish
  image: docker-registry.oxfordnanolabs.local:5000/ont-base-ubuntu:16.04
  when: manual
  tags:
    - linux
  only:
    - master
    - tags
  script:
   - for deb in ont-minion1c-driver*.deb; do
   -   arch=$(dpkg --info "${deb}" | grep "Architecture:" | cut -d ":" -f 2 | tr -d "[:space:]")
   -   url="https://artifactory.oxfordnanolabs.local/artifactory/${REPO}/pool/$(basename "${deb}");commitSHA=${CI_COMMIT_SHA};deb.distribution=${UBUNTU_VERSION};deb.component=non-free;deb.architecture=${arch}"
   -   echo "Uploading ${deb} to ${url}"
   - ' curl -LfsS
         --request PUT
         --user "${ARTIFACTORY_USER}:${ARTIFACTORY_PASS}"
         --header "X-Checksum-Sha256: $(sha256sum "${deb}" | cut -d " " -f 1)"
         --header "X-Checksum-Md5: $(md5sum "${deb}" | cut -d " " -f 1)"
         --upload-file "${deb}"
         "${url}"'
   -   echo "Artifact is available at https://artifactory.oxfordnanolabs.local/artifactory/webapp/#/artifacts/browse/tree/General/${REPO}/pool/$(basename "${deb}")"
   - done

publish_unstable:
  <<: *publish
  stage: deploy
  variables:
    REPO: ONTDev-Deb

publish_stable:
  <<: *publish
  stage: deploy
  variables:
    REPO: ONT-Deb
