FROM git.oxfordnanolabs.local:4567/traque/ont-docker-base/ont-base-ubuntu:16.04

RUN apt-get update && apt-get -y upgrade && apt-get -y install \
    build-essential \
    bc \
    debhelper \
    dkms \
    fakeroot \
    git \
    lintian \
    pandoc

ARG BUILD_TAG=minion1c_v1.1.0

RUN cd /usr/src &&\
    git clone --branch "${BUILD_TAG}" --depth 1 https://git.oxfordnanolabs.local/minit/linux-minit.git

ARG LOCALVERSION="-minit"

RUN cd /usr/src/linux-minit && make mrproper

ADD Module.symvers.${BUILD_TAG} /usr/src/linux-minit/Module.symvers
ADD config.${BUILD_TAG} /usr/src/linux-minit/.config

RUN cd /usr/src/linux-minit &&\
    make oldconfig &&\
    make modules_prepare

RUN cd /usr/src/linux-minit &&\
    KERNELVERSION="$(make -s kernelversion)$LOCALVERSION" &&\
    mkdir -p "/lib/modules/$KERNELVERSION" &&\
    ln -s "$PWD" "/lib/modules/$KERNELVERSION/build"

