ARG UBUNTU_VERSION=18.04

FROM git.oxfordnanolabs.local:4567/traque/ont-docker-base/ont-base-ubuntu:${UBUNTU_VERSION}

ARG HEADERS_PACKAGE_URL

RUN curl -LSsf -o linux-headers.deb "${HEADERS_PACKAGE_URL}" && \
    dpkg -i linux-headers.deb && \
    rm linux-headers.deb

RUN apt-get update && apt-get -y upgrade && apt-get install -y \
    build-essential \
    debhelper \
    dkms \
    fakeroot \
    lintian \
    pandoc
